Repository jenkins-x-plugins/jx-application, pull requests merged in 2022-04, with the labels that each got.

#141 fix: bump dependency versions to fix security alerts
  OWNERS
  go.mod
  go.sum
Labels: size/L

#142 fix: update go version in makefile
  Makefile
Labels: size/XS, approved, ok-to-test, lgtm

#145 chore: upgrade go version to 1.17.9
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Makefile
  go.mod
  go.sum
Labels: size/L, approved
